package com.HealthMeetProject.code.domain;

public enum Specialization {
    CARDIOLOGIST,
    DERMATOLOGIST,
    NEUROLOGIST,
    PEDIATRICIAN,
    ORTHOPEDICS,
    OPHTHALMOLOGIST,
    GYNECOLOGIST,
    UROLOGIST,
    ONCOLOGIST,
    GASTROENTEROLOGIST,
    ENDOCRINOLOGIST,
    PULMONOLOGIST,
    HEMATOLOGIST,
    PSYCHIATRIST
}
